### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by QuaserEatingATaco**
I made a Dutch translation file cpp thingy (Which has instructions for themeplaza instead of 3dsthemes)  and should have added the code to make it actually work.....

But i dont know c++ nor can i compile it right now as i dont have everything needed installed and the current internet situation struggles with even basic websites. (I got bored on vacation alright) But it shouldnt explode the universe.....

### CODE REVIEW

**Comment by ihaveamac** [comment]
oh, nearly forgot about this. I'll try building it when I can.

**Comment by ghost** [comment]
I think you've forgotten about this

**Comment by ihaveamac** [comment]
I will merge this and update this one last time, since we have a new manager.

**Comment by ihaveamac** [comment]
sorry for getting to this so late. thanks for the PR!

**Pull request merged**
